[default]
database = "dev"

[migration.default]
versioned = "./migrations/versioned"
repeatable = [
	"./migrations/repeatable",
	"./migrations/views",
	"./migrations/packages",
	"./migrations/gtt",
]

[database.dev]
url = "${DATABASE_URL}"
migration = "default"
categories = { env = "dev" }
