[default]
database = "dev"

[migration.default]
versioned = "./migrations/versioned"
repeatable = "./migrations/repeatable"

[database.dev]
url = "sqlite://example.sqlite"
migration = "default"
categories = { env = "dev" }
